set(OPENAL_ROOT ${CMAKE_BINARY_DIR}/openal)
if(TARGET_WIN32)
    set(ALSOFT_STATIC_LIBGCC TRUE)
    set(ALSOFT_STATIC_STDCXX TRUE)
    set(EXTRA_LIBS ole32 shell32 user32)
else()
    set(ALSOFT_STATIC_LIBGCC FALSE)
    set(ALSOFT_STATIC_STDCXX FALSE)
endif()

if(PLAT_MINGW_X86_32)
    set(CAN_WE_SSE FALSE)
else()
    set(CAN_WE_SSE TRUE)
endif()

# Static OpenAL on iOS, to avoid having to repackage dylibs as frameworks
if(OPENAL_BUILD_STATIC)
    set(ALSOFT_LIBTYPE "STATIC")
else()
    set(ALSOFT_LIBTYPE "SHARED")
endif()

# Added: on iOS CoreAudio is the only real output backend. Without it OpenAL
# Soft still builds (null backend only) and every sound effect is silent, so
# fail the build instead.
if(OPENAL_BUILD_STATIC AND APPLE)
    set(ALSOFT_REQUIRE_COREAUDIO TRUE)
else()
    set(ALSOFT_REQUIRE_COREAUDIO FALSE)
endif()

# *Replicate* variables generated by `FindOpenAL`
set(OPENAL_FOUND TRUE)
set(OPENAL_COMPILING_FROM_SRC TRUE)
set(OPENAL_INCLUDE_DIR ${OPENAL_ROOT}/include/AL)
if(TARGET_WIN32)
    set(OPENAL_LIBRARY ${OPENAL_ROOT}/lib/${CMAKE_IMPORT_LIBRARY_PREFIX}OpenAL32${CMAKE_IMPORT_LIBRARY_SUFFIX})
elseif(OPENAL_BUILD_STATIC)
    set(OPENAL_LIBRARY ${OPENAL_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}openal${CMAKE_STATIC_LIBRARY_SUFFIX})
else()
    set(OPENAL_LIBRARY ${OPENAL_ROOT}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}openal${CMAKE_SHARED_LIBRARY_SUFFIX})
endif()
set(OPENAL_VERSION_STRING 1.23.1)

ExternalProject_Add(
    OPENAL
    SOURCE_DIR          ${CMAKE_SOURCE_DIR}/lib/openal
    BINARY_DIR          ${OPENAL_ROOT}
    INSTALL_DIR         ${OPENAL_ROOT}
    UPDATE_DISCONNECTED TRUE
    CMAKE_ARGS          --toolchain ${CMAKE_TOOLCHAIN_FILE}
                        --install-prefix ${OPENAL_ROOT}
                        -DCMAKE_INSTALL_LIBDIR=lib
                        -DCMAKE_BUILD_TYPE:STRING=Release
                        -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
                        -DLIBTYPE:STRING=${ALSOFT_LIBTYPE}
                        -DALSOFT_REQUIRE_COREAUDIO:BOOL=${ALSOFT_REQUIRE_COREAUDIO}
                        -DALSOFT_UTILS:BOOL=FALSE
                        -DALSOFT_NO_CONFIG_UTIL:BOOL=TRUE
                        -DALSOFT_EXAMPLES:BOOL=FALSE
                        -DALSOFT_INSTALL_CONFIG:BOOL=FALSE
                        -DALSOFT_INSTALL_HRTF_DATA:BOOL=FALSE
                        -DALSOFT_INSTALL_AMBDEC_PRESETS:BOOL=FALSE
                        -DALSOFT_INSTALL_EXAMPLES:BOOL=FALSE
                        -DALSOFT_INSTALL_UTILS:BOOL=FALSE
                        -DALSOFT_UPDATE_BUILD_VERSION:BOOL=TRUE
                        -DALSOFT_CPUEXT_SSE:BOOL=${CAN_WE_SSE}
                        -DALSOFT_CPUEXT_SSE2:BOOL=${CAN_WE_SSE}
                        -DALSOFT_CPUEXT_SSE3:BOOL=${CAN_WE_SSE}
                        -DALSOFT_CPUEXT_SSE4_1:BOOL=${CAN_WE_SSE}
                        -DALSOFT_STATIC_LIBGCC:BOOL=${ALSOFT_STATIC_LIBGCC}
                        -DALSOFT_STATIC_STDCXX:BOOL=${ALSOFT_STATIC_STDCXX}
                        -DCMAKE_POLICY_VERSION_MINIMUM=3.5
    CMAKE_CACHE_ARGS    -DEXTRA_LIBS:STRINGS=${EXTRA_LIBS}
    BUILD_BYPRODUCTS    ${OPENAL_LIBRARY}
)

# OpenAL targets
if(NOT TARGET OpenAL::OpenAL)
    if(OPENAL_BUILD_STATIC)
        add_library(OpenAL::OpenAL STATIC IMPORTED)
    else()
        add_library(OpenAL::OpenAL SHARED IMPORTED)
    endif()
endif()
add_dependencies(OpenAL::OpenAL OPENAL)
file(MAKE_DIRECTORY ${OPENAL_INCLUDE_DIR})
set_target_properties(
    OpenAL::OpenAL PROPERTIES
    IMPORTED_LOCATION ${OPENAL_LIBRARY}
    IMPORTED_IMPLIB ${OPENAL_LIBRARY}
)
target_include_directories(OpenAL::OpenAL INTERFACE ${OPENAL_INCLUDE_DIR})
target_link_directories(OpenAL::OpenAL INTERFACE ${OPENAL_ROOT}/lib)

if(OPENAL_BUILD_STATIC)
    # A static libopenal does not drag in its own transitive deps the way the
    # dylib did: OpenAL Soft is C++ and its Apple backend is CoreAudio.
    target_compile_definitions(OpenAL::OpenAL INTERFACE AL_LIBTYPE_STATIC)
    if(APPLE)
        target_link_libraries(OpenAL::OpenAL INTERFACE
            "-framework AudioToolbox" "-framework CoreAudio" c++)
    endif()
endif()
