// FBNeo romset catalog and identification by CRC-32 + size.
//
// The catalog is the driver list compiled into our own FBNeo cores (one file
// per core, generated by scripts/build-catalog.ts into native/build/), so an
// upload is judged against exactly the sets the emulator can run.
//
// How the libretro FBNeo core finds ROMs (src/burner/libretro/libretro.cpp,
// open_archive + locate_archive), which this module mirrors:
//   * it opens up to three zips from the game's directory: <set>.zip, the
//     board/BIOS zip (szBoardROM, e.g. neogeo.zip) and the parent's zip;
//   * every ROM of the set's list is looked up by CRC in any of them (names
//     are irrelevant), and a found ROM must also have the exact size;
//   * ROMs flagged NODUMP, with a zero CRC/size/type are never needed;
//     ROMs flagged OPT may be absent; everything else is required.
// For Neo Geo games the set's list includes the board's BIOS ROMs, so with
// the default MVS mode the required BIOS files are the non-optional BIOS
// entries (sp-s3.sp1, sm1.sm1, sfix.sfix, 000-lo.lo).

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { Core } from '../../shared/emu/core.ts';
import { SYSTEMS, type SystemId } from '../../shared/systems.ts';
import type { RoomMode } from '../adapters/types.ts';
import type { ValidationFinding } from './types.ts';

// BurnRomInfo.nType bits (src/burn/burn.h).
export const BRF = {
  PRG: 1 << 20,
  GRA: 1 << 21,
  SND: 1 << 22,
  ESS: 1 << 24,
  BIOS: 1 << 25,
  SELECT: 1 << 26,
  OPT: 1 << 27,
  NODUMP: 1 << 28,
} as const;

// Driver flags (BDF_*).
export const BDF = {
  WORKING: 1 << 0,
  BOARDROM: 1 << 3,
  CLONE: 1 << 4,
  BOOTLEG: 1 << 5,
  PROTOTYPE: 1 << 6,
  HACK: 1 << 7,
  HOMEBREW: 1 << 8,
  DEMO: 1 << 9,
} as const;

// Genre flags (GBF_*).
export const GBF = {
  HORSHOOT: 1 << 0,
  VERSHOOT: 1 << 1,
  SCRFIGHT: 1 << 2,   // beat 'em up
  VSFIGHT: 1 << 3,    // versus fighter
  BIOS: 1 << 4,
  BREAKOUT: 1 << 5,
  CASINO: 1 << 6,
  BALLPADDLE: 1 << 7,
  MAZE: 1 << 8,
  MINIGAMES: 1 << 9,
  PINBALL: 1 << 10,
  PLATFORM: 1 << 11,
  PUZZLE: 1 << 12,
  QUIZ: 1 << 13,
  SPORTSMISC: 1 << 14,
  SPORTSFOOTBALL: 1 << 15,
  MISC: 1 << 16,
  MAHJONG: 1 << 17,
  RACING: 1 << 18,
  SHOOT: 1 << 19,
  MULTISHOOT: 1 << 20,
  ACTION: 1 << 21,
  RUNGUN: 1 << 22,
  STRATEGY: 1 << 23,
} as const;

const GENRE_LABELS: [number, string][] = [
  [GBF.VSFIGHT, 'Fighting'],
  [GBF.SCRFIGHT, "Beat 'em up"],
  [GBF.RUNGUN, "Run 'n gun"],
  [GBF.HORSHOOT, 'Shooter'],
  [GBF.VERSHOOT, 'Shooter'],
  [GBF.SHOOT, 'Shooter'],
  [GBF.MULTISHOOT, 'Shooter'],
  [GBF.PLATFORM, 'Platform'],
  [GBF.ACTION, 'Action'],
  [GBF.PUZZLE, 'Puzzle'],
  [GBF.SPORTSMISC, 'Sports'],
  [GBF.SPORTSFOOTBALL, 'Sports'],
  [GBF.RACING, 'Racing'],
  [GBF.QUIZ, 'Quiz'],
  [GBF.MAZE, 'Maze'],
  [GBF.BREAKOUT, 'Breakout'],
  [GBF.BALLPADDLE, 'Ball & paddle'],
  [GBF.PINBALL, 'Pinball'],
  [GBF.MINIGAMES, 'Mini-games'],
  [GBF.STRATEGY, 'Strategy'],
  [GBF.MAHJONG, 'Mahjong'],
  [GBF.CASINO, 'Casino'],
  [GBF.MISC, 'Misc'],
];

export const CATALOG_SYSTEMS: SystemId[] = ['fbneo_cps12', 'fbneo_neogeo'];

export interface CatalogRom {
  n: string;   // name in the set
  s: number;   // size in bytes
  c: number;   // CRC-32 (unsigned)
  t: number;   // BRF_* type bits
}

export interface CatalogSet {
  name: string;
  fullname: string;
  parent: string;
  board: string;
  samples: string;
  players: number;
  genre: number;
  flags: number;
  year: string;
  manufacturer: string;
  hardware: string;
  // 1 = this set also lists every BIOS ROM of its board set; they are
  // omitted from `roms` to keep the file small and restored on load.
  boardBios?: 1;
  roms: CatalogRom[];
}

export interface CatalogFile {
  format: 1;
  core: string;
  coreVersion: string;
  build: Record<string, unknown>;
  generatedAt: string;
  sets: CatalogSet[];
}

export interface ResolvedSet extends CatalogSet {
  system: SystemId;
  full: CatalogRom[];   // complete ROM list as the driver reports it
}

export interface SetSummary {
  system: SystemId;
  name: string;
  fullname: string;
  parent: string | null;
  board: string | null;
  players: number;
  genre: number;
  flags: number;
  year: string;
  manufacturer: string;
  hardware: string;
  samples: string | null;
}

export interface DependencyNeed {
  kind: 'bios' | 'parent';
  set: string;
  files: string[];
}

export interface Identification {
  result: 'identified' | 'ambiguous' | 'incomplete' | 'unknown';
  system: SystemId | null;
  set: SetSummary | null;          // identified set, or the closest match when incomplete
  kind: 'game' | 'bios' | 'parent';
  complete: boolean;               // every required file is in this zip or provided by a dependency set
  needs: DependencyNeed[];         // files that must come from the parent / board zip
  matchedRoms: number;             // required ROMs present in this zip
  totalRoms: number;               // required ROMs of the set in total
  candidates: string[];            // ambiguous: the sets it could be
  findings: ValidationFinding[];
  message: string;                 // one human-readable sentence
}

export interface ZipFileInfo {
  name: string;
  size: number;
  crc: number;
}

// ---------------------------------------------------------------- rules

// Never needed by the libretro core (open_archive marks these STAT_SKIP).
export function isSkippedRom(r: CatalogRom): boolean {
  return (r.t & BRF.NODUMP) !== 0 || r.t === 0 || r.s === 0 || r.c === 0;
}

export function isRequiredRom(r: CatalogRom): boolean {
  return !isSkippedRom(r) && (r.t & BRF.OPT) === 0;
}

const romKey = (crc: number, size: number) => `${crc >>> 0}:${size}`;

export function genreLabel(genre: number): string | null {
  const out: string[] = [];
  for (const [bit, label] of GENRE_LABELS) if (genre & bit && !out.includes(label)) out.push(label);
  return out.length ? out.join(', ') : null;
}

// Room mode from the catalog genre: fighters are versus, beat 'em ups are
// co-op, other one-player games are single, everything else co-op.
export function defaultModeFor(set: { system: SystemId; players: number; genre: number }): { mode: RoomMode; players: number } {
  const max = SYSTEMS[set.system].maxPorts;
  const players = Math.max(1, Math.min(max, set.players || 1));
  if (set.genre & GBF.VSFIGHT) return { mode: 'versus', players: Math.max(2, players) };
  if (set.genre & GBF.SCRFIGHT) return { mode: 'coop', players };
  return { mode: players === 1 ? 'single' : 'coop', players };
}

export function describeSet(s: { name: string; fullname: string }): string {
  return `FBNeo set ${s.name} (${s.fullname})`;
}

// ---------------------------------------------------------------- building

function sameRom(a: CatalogRom, b: CatalogRom): boolean {
  return a.n === b.n && a.s === b.s && a.c === b.c && a.t === b.t;
}

// Turns the raw driver list from Core.catalog() into a CatalogFile.
// Duplicate driver names keep the board (BDF_BOARDROM) entry: the Neo Geo
// build lists "neogeo" twice, as the BIOS board games refer to and as a
// playable "MVS system" driver.
export function compactCatalog(core: string, coreVersion: string, build: Record<string, unknown>, raw: any[]): { file: CatalogFile; notes: string[] } {
  const notes: string[] = [];
  const byName = new Map<string, CatalogSet>();
  for (const d of raw) {
    if (!d || typeof d.name !== 'string' || !d.name) continue;
    const set: CatalogSet = {
      name: d.name,
      fullname: String(d.fullname ?? ''),
      parent: String(d.parent ?? ''),
      board: String(d.board ?? ''),
      samples: String(d.samples ?? ''),
      players: Number(d.players) || 0,
      genre: Number(d.genre) >>> 0,
      flags: Number(d.flags) >>> 0,
      year: String(d.date ?? ''),
      manufacturer: String(d.manufacturer ?? ''),
      hardware: String(d.system ?? ''),
      roms: (Array.isArray(d.roms) ? d.roms : []).map((r: any) => ({ n: String(r.n), s: Number(r.s) >>> 0, c: Number(r.c) >>> 0, t: Number(r.t) >>> 0 })),
    };
    const prev = byName.get(set.name);
    if (prev) {
      const keepNew = (set.flags & BDF.BOARDROM) !== 0 && (prev.flags & BDF.BOARDROM) === 0;
      notes.push(`duplicate driver name ${set.name}: kept "${keepNew ? set.fullname : prev.fullname}"`);
      if (keepNew) byName.set(set.name, set);
      continue;
    }
    byName.set(set.name, set);
  }
  let compacted = 0;
  for (const set of byName.values()) {
    const board = set.board ? byName.get(set.board) : undefined;
    if (!board) continue;
    const boardBios = board.roms.filter((r) => r.t & BRF.BIOS);
    if (boardBios.length === 0) continue;
    const mine = set.roms.filter((r) => r.t & BRF.BIOS);
    if (mine.length === boardBios.length && mine.every((r, i) => sameRom(r, boardBios[i]))) {
      set.roms = set.roms.filter((r) => !(r.t & BRF.BIOS));
      set.boardBios = 1;
      compacted++;
    }
  }
  if (compacted) notes.push(`${compacted} sets share their board's BIOS list (stored once)`);
  return {
    file: { format: 1, core, coreVersion, build, generatedAt: new Date().toISOString(), sets: [...byName.values()] },
    notes,
  };
}

export function catalogPath(dir: string, core: string): string {
  return join(dir, `catalog-${core}.json`);
}

// native/build-cores.sh records the sources of the build (e.g. the FBNeo commit).
function readBuildInfo(coreDir: string): Record<string, unknown> {
  try {
    const b = JSON.parse(readFileSync(join(coreDir, 'build-info.json'), 'utf8'));
    return b && typeof b === 'object' ? b : {};
  } catch {
    return {};
  }
}

// A catalog generated from other FBNeo sources than the cores in the
// directory describes another driver list (sets, ROM CRCs, BIOS needs).
// Unknown provenance on either side is not treated as stale.
export function isStaleCatalog(file: CatalogFile, build: Record<string, unknown>): boolean {
  const now = build.fbneo;
  const then = file.build?.fbneo;
  return typeof now === 'string' && typeof then === 'string' && now !== then;
}

// Builds a catalog straight from a compiled core (used by the build script,
// and as a fallback when the JSON is missing or stale).
export async function catalogFromCore(coreDir: string, core: string): Promise<{ file: CatalogFile; notes: string[] }> {
  const mod = await import(pathToFileURL(join(coreDir, `${core}.mjs`)).href);
  const c = await Core.create(mod.default, readFileSync(join(coreDir, `${core}.wasm`)), { quiet: true });
  return compactCatalog(core, c.version, readBuildInfo(coreDir), c.catalog());
}

// ---------------------------------------------------------------- catalog

interface Evaluation {
  set: ResolvedSet;
  distinctivePresent: number;
  required: number;
  presentRequired: number;
  missingOwn: CatalogRom[];
  fromParent: CatalogRom[];
  fromBoard: CatalogRom[];
  extras: ZipFileInfo[];
}

export class RomCatalog {
  readonly cores: { system: SystemId; coreVersion: string; build: Record<string, unknown> }[] = [];
  private readonly sets = new Map<string, ResolvedSet>();
  private readonly byKey = new Map<string, ResolvedSet[]>();   // own ROM list only
  private readonly byCrc = new Map<number, ResolvedSet[]>();
  private readonly parents = new Set<string>();

  static fromFiles(files: CatalogFile[]): RomCatalog {
    const cat = new RomCatalog();
    for (const f of files) cat.add(f);
    return cat;
  }

  // Loads catalog-<core>.json for each FBNeo core found in `dir`.
  static load(dir: string): RomCatalog {
    const files: CatalogFile[] = [];
    for (const core of CATALOG_SYSTEMS) {
      const p = catalogPath(dir, core);
      if (existsSync(p)) files.push(JSON.parse(readFileSync(p, 'utf8')));
    }
    return RomCatalog.fromFiles(files);
  }

  // Like load(), but builds a catalog from the core in memory when its JSON
  // is missing, or stale because the core was rebuilt from other FBNeo
  // sources without running scripts/build-catalog.ts (slower, but uploads
  // are judged against the driver list that will actually run them).
  static async loadOrBuild(dir: string): Promise<RomCatalog> {
    const build = readBuildInfo(dir);
    const files: CatalogFile[] = [];
    for (const core of CATALOG_SYSTEMS) {
      const p = catalogPath(dir, core);
      const hasCore = existsSync(join(dir, `${core}.wasm`));
      let file: CatalogFile | null = existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : null;
      if (file && hasCore && isStaleCatalog(file, build)) file = null;
      if (!file && hasCore) file = (await catalogFromCore(dir, core)).file;
      if (file) files.push(file);
    }
    return RomCatalog.fromFiles(files);
  }

  get systems(): SystemId[] {
    return this.cores.map((c) => c.system);
  }

  private add(f: CatalogFile): void {
    if (f.format !== 1 || !CATALOG_SYSTEMS.includes(f.core as SystemId)) return;
    const system = f.core as SystemId;
    this.cores.push({ system, coreVersion: f.coreVersion, build: f.build });
    const local = new Map(f.sets.map((s) => [s.name, s]));
    for (const s of f.sets) {
      let full = s.roms;
      if (s.boardBios) {
        const board = local.get(s.board);
        if (board) full = [...s.roms, ...board.roms.filter((r) => r.t & BRF.BIOS)];
      }
      const rs: ResolvedSet = { ...s, system, full };
      this.sets.set(`${system}:${s.name}`, rs);
      if (s.parent) this.parents.add(`${system}:${s.parent}`);
      for (const r of s.roms) {
        if (isSkippedRom(r)) continue;
        const k = romKey(r.c, r.s);
        const list = this.byKey.get(k);
        if (!list) this.byKey.set(k, [rs]);
        else if (!list.includes(rs)) list.push(rs);
        const cl = this.byCrc.get(r.c);
        if (!cl) this.byCrc.set(r.c, [rs]);
        else if (!cl.includes(rs)) cl.push(rs);
      }
    }
  }

  get(system: SystemId, name: string): ResolvedSet | null {
    return this.sets.get(`${system}:${name}`) ?? null;
  }

  hasClones(system: SystemId, name: string): boolean {
    return this.parents.has(`${system}:${name}`);
  }

  summary(s: ResolvedSet): SetSummary {
    return {
      system: s.system,
      name: s.name,
      fullname: s.fullname,
      parent: s.parent || null,
      board: s.board || null,
      players: s.players,
      genre: s.genre,
      flags: s.flags,
      year: s.year,
      manufacturer: s.manufacturer,
      hardware: s.hardware,
      samples: s.samples || null,
    };
  }

  kindOf(s: ResolvedSet): 'game' | 'bios' | 'parent' {
    if (s.flags & BDF.BOARDROM) return 'bios';
    // A parent the emulator cannot run is only useful as a dependency.
    if (!(s.flags & BDF.WORKING) && this.hasClones(s.system, s.name)) return 'parent';
    return 'game';
  }

  // Files of `s` that are required but not in `have` (crc:size keys), split
  // by where they can come from.
  private evaluate(s: ResolvedSet, present: Map<string, ZipFileInfo>, files: ZipFileInfo[]): Evaluation {
    const parent = s.parent ? this.get(s.system, s.parent) : null;
    const board = s.board ? this.get(s.system, s.board) : null;
    const keysOf = (x: ResolvedSet | null) => new Set(x ? x.full.filter((r) => !isSkippedRom(r)).map((r) => romKey(r.c, r.s)) : []);
    const parentKeys = keysOf(parent);
    const boardKeys = keysOf(board);
    const known = new Set<string>();
    const ev: Evaluation = { set: s, distinctivePresent: 0, required: 0, presentRequired: 0, missingOwn: [], fromParent: [], fromBoard: [], extras: [] };
    for (const r of s.full) {
      if (isSkippedRom(r)) continue;
      const k = romKey(r.c, r.s);
      known.add(k);
      const inZip = present.has(k);
      if (inZip && !parentKeys.has(k) && !boardKeys.has(k)) ev.distinctivePresent++;
      if (!isRequiredRom(r)) continue;
      ev.required++;
      if (inZip) ev.presentRequired++;
      else if (boardKeys.has(k)) ev.fromBoard.push(r);
      else if (parentKeys.has(k)) ev.fromParent.push(r);
      else ev.missingOwn.push(r);
    }
    ev.extras = files.filter((f) => !known.has(romKey(f.crc, f.size)));
    return ev;
  }

  // Identifies a zip from its entries' CRC-32 and sizes. `fileNameHint` (the
  // uploaded file name) only breaks ties between equally valid readings.
  identify(files: ZipFileInfo[], fileNameHint = ''): Identification {
    const findings: ValidationFinding[] = [];
    const present = new Map<string, ZipFileInfo>();
    for (const f of files) present.set(romKey(f.crc, f.size), f);
    const base: Identification = {
      result: 'unknown', system: null, set: null, kind: 'game', complete: false, needs: [],
      matchedRoms: 0, totalRoms: 0, candidates: [], findings, message: '',
    };
    if (this.cores.length === 0) {
      base.message = 'arcade romset catalogs are not available on this server';
      findings.push({ level: 'error', code: 'catalog_missing', message: base.message });
      return base;
    }

    const cand = new Set<ResolvedSet>();
    for (const f of files) for (const s of this.byKey.get(romKey(f.crc, f.size)) ?? []) cand.add(s);
    const evals = [...cand].map((s) => this.evaluate(s, present, files)).filter((e) => e.distinctivePresent > 0);

    if (evals.length === 0) {
      // Same CRC but a different size usually means an overdump/underdump.
      const sizeOnly = files.filter((f) => this.byCrc.has(f.crc));
      if (sizeOnly.length) {
        findings.push({
          level: 'error',
          code: 'bad_dump',
          message: `${sizeOnly.length} file(s) match known ROM checksums but have the wrong size (bad dump?)`,
        });
      }
      base.message = `this zip does not match any romset supported here (${this.supportedText()}); it may be for another arcade system, or a modified/renamed dump`;
      findings.push({ level: 'error', code: 'unknown_romset', message: base.message });
      return base;
    }

    const complete = evals.filter((e) => e.missingOwn.length === 0);
    if (complete.length === 0) return this.incomplete(evals, files, base);

    const hint = fileNameHint.replace(/^.*[\\/]/, '').replace(/\.[^.]*$/, '').toLowerCase();
    let chosen: Evaluation | null = null;
    let why = '';
    if (complete.length === 1) {
      chosen = complete[0];
    } else {
      const byHint = complete.filter((e) => e.set.name === hint);
      if (byHint.length === 1) {
        chosen = byHint[0];
        why = `the zip matches ${complete.length} sets; chose ${chosen.set.name} because of the file name`;
      } else {
        // A merged set: the parent's zip also carries its clones' files.
        const roots = complete.filter((e) => complete.every((o) => o === e || (o.set.parent === e.set.name && o.set.system === e.set.system)));
        if (roots.length === 1) {
          chosen = roots[0];
          const clones = complete.filter((e) => e !== chosen).map((e) => e.set.name);
          findings.push({
            level: 'info',
            code: 'merged_set',
            message: `merged romset: also contains files of ${clones.length} clone set(s) (${clones.slice(0, 5).join(', ')}${clones.length > 5 ? ', ...' : ''}); upload a clone's own zip to play it`,
          });
        } else {
          const rank = [...complete].sort((a, b) => b.presentRequired - a.presentRequired || a.extras.length - b.extras.length);
          const [a, b] = rank;
          if (a.presentRequired !== b.presentRequired || a.extras.length !== b.extras.length) chosen = a;
        }
      }
    }
    if (!chosen) {
      base.result = 'ambiguous';
      base.candidates = complete.map((e) => e.set.name).sort();
      base.message = `this zip matches several romsets equally well (${base.candidates.slice(0, 6).join(', ')}); rename it to the intended set name (e.g. ${base.candidates[0]}.zip) and upload again`;
      findings.push({ level: 'error', code: 'ambiguous_romset', message: base.message });
      return base;
    }
    if (why) findings.push({ level: 'info', code: 'name_tiebreak', message: why });
    return this.identified(chosen, base);
  }

  private identified(e: Evaluation, base: Identification): Identification {
    const s = e.set;
    const out = base;
    out.result = 'identified';
    out.system = s.system;
    out.set = this.summary(s);
    out.kind = this.kindOf(s);
    out.complete = true;
    out.matchedRoms = e.presentRequired;
    out.totalRoms = e.required;
    if (e.fromBoard.length) {
      const board = this.get(s.system, s.board);
      out.needs.push({ kind: board && board.flags & BDF.BOARDROM ? 'bios' : 'parent', set: s.board, files: e.fromBoard.map((r) => r.n) });
    }
    if (e.fromParent.length) out.needs.push({ kind: 'parent', set: s.parent, files: e.fromParent.map((r) => r.n) });
    const f = out.findings;
    if (!(s.flags & BDF.WORKING) && !(s.flags & BDF.BOARDROM)) {
      f.push({ level: 'warn', code: 'not_working', message: 'FBNeo marks this romset as not working; it will probably not be playable' });
    }
    if (s.flags & BDF.BOOTLEG) f.push({ level: 'info', code: 'bootleg', message: 'bootleg romset' });
    if (s.flags & BDF.HACK) f.push({ level: 'info', code: 'hack', message: 'hacked romset' });
    if (s.flags & BDF.HOMEBREW) f.push({ level: 'info', code: 'homebrew', message: 'homebrew romset' });
    if (s.flags & BDF.PROTOTYPE) f.push({ level: 'info', code: 'prototype', message: 'prototype romset' });
    if (s.samples) f.push({ level: 'info', code: 'samples_optional', message: `this game can use the "${s.samples}" sample set for some sounds; samples are not loaded` });
    if (e.extras.length) {
      f.push({ level: 'info', code: 'extra_files', message: `${e.extras.length} file(s) in the zip are not part of this romset and are ignored` });
    }
    const label = out.kind === 'bios' ? 'BIOS/board set' : out.kind === 'parent' ? 'parent set' : 'romset';
    out.message = `${label} ${s.name} (${s.fullname})`;
    return out;
  }

  private incomplete(evals: Evaluation[], files: ZipFileInfo[], base: Identification): Identification {
    const rank = [...evals].sort(
      (a, b) =>
        b.distinctivePresent - a.distinctivePresent ||
        b.presentRequired / Math.max(1, b.required) - a.presentRequired / Math.max(1, a.required) ||
        a.missingOwn.length - b.missingOwn.length,
    );
    const best = rank[0];
    const s = best.set;
    const out = base;
    out.result = 'incomplete';
    out.system = s.system;
    out.set = this.summary(s);
    out.kind = this.kindOf(s);
    out.matchedRoms = best.presentRequired;
    out.totalRoms = best.required;
    // Explain each missing file: absent, or present with a different checksum.
    const byName = new Map(files.map((f) => [f.name.replace(/^.*\//, '').toLowerCase(), f]));
    const details = best.missingOwn.map((r) => {
      const f = byName.get(r.n.toLowerCase());
      if (!f) return r.n;
      if (f.crc === r.c) return `${r.n} (wrong size)`;
      return `${r.n} (different CRC)`;
    });
    const list = details.slice(0, 8).join(', ') + (details.length > 8 ? `, and ${details.length - 8} more` : '');
    const closeEnough = best.presentRequired >= Math.ceil(best.required / 2);
    out.message = closeEnough
      ? `looks like ${s.name} (${s.fullname}) but ${best.missingOwn.length} required file(s) are missing or modified: ${list}`
      : `unknown or modified romset; the closest match is ${s.name} (${s.fullname}), with ${best.missingOwn.length} required file(s) missing or modified`;
    out.findings.push({ level: 'error', code: 'incomplete_romset', message: out.message });
    return out;
  }

  private supportedText(): string {
    const names = this.cores.map((c) => SYSTEMS[c.system].label);
    return names.join(' and ');
  }
}
